apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kafka
  name: sming-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sming.com
    secretName: sming-secret
  rules:
  - host: sming.com
    http:
      paths:
      - path: /kafka-ui
        pathType: Prefix
        backend:
          service:
            name: kafka-ui
            port:
              number: 8081
