kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-playground
# networking:
#   ipFamily: dual
#   apiServerAddress: 127.0.0.1
#   podSubnet: "10.244.0.0/16" # default setting
#   serviceSubnet: "10.96.0.0/12" # default setting
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    # listenAddress: 127.0.0.1
    protocol: TCP
- role: worker
  labels:
    tier: frontend
- role: worker
  labels:
    tier: backend
