apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: k8s-playground
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 31437
      hostPort: 8080
      protocol: TCP
    - containerPort: 30478
      hostPort: 8443
# - role: worker
#   labels:
#     tier: frontend
# - role: worker
#   labels:
#     tier: backend
